version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 4000:4000
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/test
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongodb
      - redis
      - rabbitmq
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
    depends_on:
      - backend
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  mongodb_data:
