version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - 4000:4000
    environment:
      - MONGODB_URI=mongodb+srv://adityamuhamadputra:RywYFwqFqnfVKylU@cluster0.aoql4.mongodb.net/
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
      - rabbitmq
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
volumes:
  mongodb_data:
